name: Deploy action
description: Deploy to Cloudflare Workers

inputs:
  cloudflare-api-token:
    description: Cloudflare API token
    required: true

  cloudflare-account-id:
    description: Cloudflare account ID
    required: true

  environment:
    description: "Cloudflare environment for deployment"
    required: false
    default: "production"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash

    - name: Build
      run: bun run build
      shell: bash

    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.cloudflare-api-token }}
        accountId: ${{ inputs.cloudflare-account-id }}
        command: deploy
      env:
        CLOUDFLARE_ENV: ${{ inputs.environment }}
